// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  hololiveapp: [
    'hololiveapp/intro',
    {
      type: 'category',
      label: 'クイックスタート',
      items: [
        { type: 'autogenerated', dirName: 'hololiveapp/quick-start' },
      ],
    },
    {
      type: 'category',
      label: 'フェイストラッキング（最高・激重）',
      items: [
        { type: 'autogenerated', dirName: 'hololiveapp/face-tracking' },
      ],
    },
    {
      type: 'category',
      label: '画面と操作説明（高・激重）',
      items: [
        { type: 'autogenerated', dirName: 'hololiveapp/screen-and-operation-description' },
      ],
    },
    {
      type: 'category',
      label: 'モデル（高・軽）',
      items: [
        { type: 'autogenerated', dirName: 'hololiveapp/model' },
      ],
    },
    {
      type: 'category',
      label: 'アクセサリー（高・激重）',
      items: [
        { type: 'autogenerated', dirName: 'hololiveapp/accessory' },
      ],
    },
    {
      type: 'category',
      label: 'コラボ機能（高・重）',
      items: [
        { type: 'autogenerated', dirName: 'hololiveapp/collabo' },
      ],
    },
    {
      type: 'category',
      label: 'ボディトラッキング（中・激重）',
      items: [
        { type: 'autogenerated', dirName: 'hololiveapp/body-tracking' },
      ],
    },
    {
      type: 'category',
      label: '顔の動き調整（中・激重）',
      items: [
        { type: 'autogenerated', dirName: 'hololiveapp/face-calibration' },
      ],
    },
    {
      type: 'category',
      label: 'モーション（低・重）',
      items: [
        { type: 'autogenerated', dirName: 'hololiveapp/motion' },
      ],
    },
    {
      type: 'category',
      label: '各種設定（中・激重）',
      items: [
        { type: 'autogenerated', dirName: 'hololiveapp/settings' },
      ],
    },
    {
      type: 'category',
      label: 'その他の機能（低・重）',
      items: [
        { type: 'autogenerated', dirName: 'hololiveapp/others' },
      ],
    },
    {
      type: 'category',
      label: 'FAQ',
      items: [
        { type: 'autogenerated', dirName: 'hololiveapp/faq' },
      ],
    },
  ],
  
  holoroom: [
      "holoroom/intro"
  ],
  
  holokaraoke: [
      "holokaraoke/intro"
  ],
};

export default sidebars;
